{% set version = "5.96" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-quantreg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/quantreg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/quantreg/quantreg_{{ version }}.tar.gz
  sha256: a2aa0638cdd626d8da0e573856177c4637841c6de143463a3fc0bbe268e6fd92

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - r-conquer                        # [build_platform != target_platform]
    - r-matrix                         # [build_platform != target_platform]
    - r-sparsem                        # [build_platform != target_platform]
    - r-matrixmodels                   # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
  host:
    - libblas
    - liblapack
    - r-base
    - r-conquer
    - r-matrix
    - r-matrixmodels
    - r-sparsem
  run:
    - r-base
    - {{ native }}gcc-libs             # [win]
    - r-conquer
    - r-matrix
    - r-matrixmodels
    - r-sparsem

test:
  commands:
    - $R -e "library('quantreg')"           # [not win]
    - "\"%R%\" -e \"library('quantreg')\""  # [win]

about:
  home: https://www.r-project.org
  license: GPL-2.0-or-later
  summary: 'Estimation and inference methods for models of conditional quantiles:  Linear and nonlinear parametric and non-parametric (total variation penalized) models  for conditional quantiles of a univariate response and several methods for handling censored survival data.  Portfolio selection methods based on expected
    shortfall risk are also included.'
  license_family: GPL3
  license_file: 
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
