{% set version = '5.36' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-quantreg
  version: {{ version|replace("-", "_") }}

source:
  fn: quantreg_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/quantreg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/quantreg/quantreg_{{ version }}.tar.gz
  sha256: ea7b410b8eaee10c7bda0c666ba57c597a3ee8ea97c6a56e16a8dc0ed56f6f08

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-matrixmodels
    - r-sparsem
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-matrixmodels
    - r-sparsem

test:
  commands:
    - $R -e "library('quantreg')"           # [not win]
    - "\"%R%\" -e \"library('quantreg')\""  # [win]

about:
  home: https://www.r-project.org
  license: GPL (>= 2)
  summary: 'Estimation and inference methods for models of conditional quantiles:  Linear and
    nonlinear parametric and non-parametric (total variation penalized) models  for
    conditional quantiles of a univariate response and several methods for handling
    censored survival data.  Portfolio selection methods based on expected shortfall
    risk are also included.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
