appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: dse9LU6MsmkiD4QHkOZOd+VQlwt/MX0ipe3kd3/WB5olKd6DIzI4y7drQIJpHxgcRZFxy9eYbKBGhUu+7kyU5uSKnYisTSyJ4jQCMJ2tjks8Q/tZXDdJeAWlCV6HmmEaTu5z9CA7oUl2EujJuPs0oirUdS0wreIvnZRfpAqhAQrhCRO2FkdZU6c8AJVvFat/7Z4rwMPxcshUW9DMzdSPUjS+vXoriARCk6PiTfvAZPCHr6qpkOYSLVcv6s3xDoFPTrgiSEIxha/eFLCHhA0us4ur3tUdg0D2ofv6HdczvR0gAgMiba+S2SIKHMZrx0RiurAB5rJuclNkkmCXlXOoAeN2Hwy5ogT8q+Y79uwxyv7/W2yA8gtjtfkmpHGtX8lYWt/BwsHuepMlP9EdApKNLbpnRl2dg2lvBVkPPj8vTvyEAcB1eBcTdhSKz4/4qGJUI4Le66etLYMY2jgEe0UroSVS71BQhUe6bVBkb4rfL3WErFBtd4vRAf38fD1ER6d7Uf70uOW5ZHcD8g5nOAmne2xjsJXB5jGZ4xX2k33NbRkPEf7Z541PL/E/X6Jml1LCuL4zBrlCWah1shNPF4Fi0fuz/2AH5nbYziMe56DckwcNDUcH4/BHUw8BCyfA9UPojg+e/x+Rtv5w2TkqjEgDJ6DEFvH435KJx9t2OVqMa/g=}
